language: python
python:
- '3.6'
services: docker
git:
  depth: false
install: make build
stages:
- name: test
- name: publish-release
  if: branch = main AND type != pull_request
- name: publish-staging
  if: branch != main AND type != pull_request
jobs:
  include:
  - stage: test
    name: Test Docker
    script:
    - make version print-pypi
    - make test-docker
  - stage: publish-staging
    name: Publish staging image
    script:
    - make publish-staging
  - stage: publish-release
    name: Publish production image
    script:
    - make publish-release
env:
  global:
  - BRANCH_NAME=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
  - secure: EumwsMq5txdhzm2VmC+ggdoWz91m3FU9sNw3STwCAcQU/fKrbSDcoeyQ5Cwzi/Fs77SlkXAq+JRO1MLZMWkksZy675alVKI4Vil1jBfXyqNQZhY482OhQdprxJ4WbPb6ejZc/YuE65k0goYdkwRZBwj32DOADbpteXqcqEs7n/htQO9Dz/C7LZd9dQaXaG8Np1eo4N/sMWhuZwCATo/atMHmRsRhA6niGYwgVSHL448NItfCoZLxYDc+fjZ2F/QaMYwA1PAhtuoxELmta24PZ6bNAq2IWTTSrRbiow0QYVsmTBFaf7qohpX2lJYhTsqJXB4rjiJaJ4DYZN+enhLhN4Xz8Tvf73qRfXAiwaZK5zaUbyrmwZa1Q/ah+VB7OZ91HnDsXjHYicxZGKHSziloMLXVMbBgvWSXpA/3rEsq8iuqyFkiKWbhaOp27m05VCLpMk5dP4QpmgGQ/Suh00sznkL2TQLD/QiYJ+2s2DVIcoGBZW40EwDlEuwbaQRIxGvGdvzi2Nf76saJUXSCteg8gzSiggv9nGHd02M/GNMPERJPO0NRZuOC4unFBn9ah59gGogS3eCp6T5hvQVZM3V3dQHay2ODChByKD3IP9MYL9/JaSm/fOi8XFTX3ZEDzciXrtG5FmKzK91BhhvT0B9cuwWnYmXPC19bki3jt9RjUJY=
  - secure: k2aFmEH82Co4ebsnikBSf8V9peltH6a+b4scoy96xLVVAC9Rz4foi9kjnL+vQ57uLjkp0UTiCOro0gzTpJVp8l5fDXuwYzROhgRZ9wAjHpE1lBoX/ZDZexUFfLFEwRzSPR9Fcg19QSfJUY/bWviPJNBMe5kJOR8TMLxspFHEU6zkRsY348TmDiadlotzIbMnZkS3jwssZbmmTkWGuM/uSVhb4BfDuNGrltwt3Y8ZLKpr+zfEldG9z2PougaZ0CHbw8T+JZokAeg8n3RQgLdY3L3GZgst0+kDIo7zBu/t15DYqc6DuzYd+/MHn1/CwR7PHuddw2DNMAvdSF60V2irtC/BXxlP0QE4FdhNNQzLssI27lzG1HZGNq6ZphSb6MG+VlxWRFzk6NZYvOptqg/iEGddFbEZxKMsLbf2vpsQzC+zFhBQonmZr32yH6kbp8OWvX8D74IXZAWXOYYSlJBpa4H28kQYULBGWQ3JQB5jDAbbRIUt2Eev5MiDOPNHigTRY5AeBkve/br+Cpdud9cKRfIpTV0U5IODB+CY78Ub70mlgl0PcNnSfkDvaEdah8tO0ObWwThE9Dw0w3aYpSLl7JQZiYJVD7CrCea47IkrZw8bDPyTgBvbCL3VY5JAsG7R4PbtKXcWDQwPU/nXj9UUIRK8uw+J7OYKc5DfrqVLzgY=
